{% set name = "py-plumed" %}
{% set version = environ['VERSION'] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../..

build:
  number: 0
  skip: True  # [win]
  # Note: --no-deps is currently required due to https://github.com/conda/conda-build/issues/3254
  # Once resolved, it should be removed.
  # script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - cython

  run:
# make sure to test with this version
    - python

test:
  requires:
    - plumed
  # TODO. In principle these could be the official regtests.
  commands:
    - python -c "import plumed; p=plumed.Plumed(); print(p)"

about:
  home: http://www.plumed.org/
  license: LGPL
  license_file: COPYING.LESSER
  summary: 'Python wrappers for plumed library'
  description: >
    PLUMED is an open source library for free energy calculations in
    molecular systems which works together with some of the most
    popular molecular dynamics engines.
  doc_url: https://plumed.github.io/doc-v2.5/user-doc/html/index.html
  dev_url: https://github.com/plumed/plumed2

