name: CI

on:
  push:
  pull_request:

jobs:
  codecheck:
    env:
      CC: gcc
      CXX: g++
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set path
      run: |
         echo "$HOME/opt/bin" >> $GITHUB_PATH
    - name: Install requirements
      run: |
        ./.travis/install.cppcheck 1.88
        ./.travis/install.gawk 5.0.1
    - name: Build astyle
      run: |
        make -j 4 -C astyle
    - name: Checking code
      run: |
        # this is required so as to have all the include files in place
        # notice that this is done automatically in build
        make -C src/lib/ dirslinks
        make codecheck

  macports:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        variant: [ "" , "+allmodules" ]
        # see https://github.community/t/how-to-conditionally-include-exclude-items-in-matrix-eg-based-on-branch/16853/6 for possible exclusions
    env:
      PYVERS: "py36 py37"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.macports-ci-ccache
        key: ccache-macports-${{ matrix.variant }}-${{ github.sha }}
        restore-keys: ccache-macports-${{ matrix.variant }}-
    - name: Install MacPorts
      run: |
        wget https://raw.githubusercontent.com/GiovanniBussi/macports-ci/master/macports-ci
        source ./macports-ci install
        source ./macports-ci ccache
    - name: Build local Portfile
      run: |
        make macports
        source ./macports-ci localports macports
    - name: Build PLUMED
      run: |
        sudo port -N -k install plumed ${{ matrix.variant }}
        plumed config show
        for p in $PYVERS ; do
          sudo port -N install $p-plumed
        done
        source ./macports-ci ccache --save
    - name: Run tests
      run: |
        # these can fail for numerical reasons in Catalina with v2.5
        sudo port -N -d test plumed ${{ matrix.variant }} || true
        for p in $PYVERS ; do
          sudo port test $p-plumed
        done
