name: CI

on:
  push:
  pull_request:

env:
# on CI, better dump stack trace in case there is an error
  PLUMED_STACK_TRACE: yes
# use two threads for openMP tests
  PLUMED_NUM_THREADS: 2
# these are used to build required packages
  CC: gcc
  CXX: g++

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        variant:
        - -doc-mpi-
        - -debug-
        - -debug-mpi-
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.ccache
        key: ccache-linux${{ matrix.variant }}hash-${{ github.sha }}
        restore-keys: ccache-linux${{ matrix.variant }}hash-
    - name: Set paths
      run: |
        echo "$HOME/opt/bin" >> $GITHUB_PATH
        echo "CPATH=$HOME/opt/include:$CPATH" >> $GITHUB_ENV
        echo "INCLUDE=$HOME/opt/include:$INCLUDE" >> $GITHUB_ENV
        echo "LIBRARY_PATH=$HOME/opt/lib:$LIBRARY_PATH" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$HOME/opt/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
    - name: Install generic packages
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y libatlas-base-dev
        sudo apt-get install -y libmatheval-dev
        sudo apt-get install -y libfftw3-dev
        sudo apt-get install -y gsl-bin
        sudo apt-get install -y libgsl0-dev
        sudo apt-get install -y ccache
        ./.travis/install.xdrfile
    - name: Install system boost
      if: ${{ ! contains( matrix.variant, '-debug-' ) }}
      run: |
        sudo apt-get install -y libboost-serialization-dev
    - name: Install boost with debug flags
      if: contains( matrix.variant, '-debug-' )
      run: |
        .travis/install.boost
    - name: Install Doxygen
      if: contains( matrix.variant, '-doc-' )
      run: |
        sudo apt-get install -y graphviz
        sudo apt-get install -y doxygen-latex
        ./.travis/install.doxygen Release_1_8_14
        ./.travis/install.lcov v1.13
        echo "PLUMED_CONFIG=$PLUMED_CONFIG --enable-gcov --enable-pdfdoc CXXFLAGS=-O0" >> $GITHUB_ENV
    - name: Setup debug flags
      if: contains( matrix.variant, '-debug-' )
      run: |
        echo "PLUMED_CONFIG=$PLUMED_CONFIG --enable-debug --enable-debug-glibcxx" >> $GITHUB_ENV
    - name: Install MPI
      # install MPI at last since it modifies CC and CXX
      if: contains( matrix.variant, '-mpi-' )
      run: |
        sudo apt-get install -y libopenmpi-dev openmpi-bin
        echo "CC=mpicc" >> $GITHUB_ENV
        echo "CXX=mpic++" >> $GITHUB_ENV
        echo "PLUMED_MPIRUN=mpirun --mca btl_base_verbose 0 --mca btl_base_warn_component_unused 0" >> $GITHUB_ENV
    - name: Build PLUMED
      run: |
        ccache -s
        ./configure --enable-boost_serialization --enable-fftw --disable-dependency-tracking --enable-modules=all LDFLAGS=-Wl,-rpath,$LD_LIBRARY_PATH $PLUMED_CONFIG
        make -j 4
        make install prefix="$HOME/opt"
        ccache -s
    - name: Run tests
      run: |
         make --no-print-directory -C regtest
         # these can fail for numerical reasons
         make -C regtest checkfail || true
    - name: Build doc
      if: contains( matrix.variant, '-doc-' )
      run: |
         make -C developer-doc coverage
         make doc >/dev/null

  codecheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set path
      run: |
         echo "$HOME/opt/bin" >> $GITHUB_PATH
    - name: Install requirements
      run: |
        ./.travis/install.cppcheck 1.88
        ./.travis/install.gawk 5.0.1
    - name: Build astyle
      run: |
        make -j 4 -C astyle
    - name: Checking code
      run: |
        # this is required so as to have all the include files in place
        # notice that this is done automatically in build
        make -C src/lib/ dirslinks
        make codecheck

  macports:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        variant: [ "" , "+allmodules" ]
        # see https://github.community/t/how-to-conditionally-include-exclude-items-in-matrix-eg-based-on-branch/16853/6 for possible exclusions
    env:
      PYVERS: "py36 py37"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.macports-ci-ccache
        key: ccache-macports-${{ matrix.variant }}-${{ github.sha }}
        restore-keys: ccache-macports-${{ matrix.variant }}-
    - name: Install MacPorts
      run: |
        wget https://raw.githubusercontent.com/GiovanniBussi/macports-ci/master/macports-ci
        source ./macports-ci install
        source ./macports-ci ccache
    - name: Build local Portfile
      run: |
        make macports
        source ./macports-ci localports macports
    - name: Build PLUMED
      run: |
        sudo port -N -k install plumed ${{ matrix.variant }}
        plumed config show
        for p in $PYVERS ; do
          sudo port -N install $p-plumed
        done
        source ./macports-ci ccache --save
    - name: Run tests
      run: |
        # these can fail for numerical reasons in Catalina with v2.5
        sudo port -N -d test plumed ${{ matrix.variant }} || true
        for p in $PYVERS ; do
          sudo port test $p-plumed
        done
